### ISSUE TITLE
What does this code do?

### ISSUE THREAD

**Issue by Andrewzekid** [KIT-2nd-Generation/KIT-2nd-Generation.github.io#1]
Ive noticed that constantderivative has been commiting to this repo pretty frequently. I would also like to help this project and thus would like some context on what is going on.

**Comment by Tatsunori-Ono** [comment]
Hey Andrew!

I think Tyler is doing a lot of work by himself (self-studying) so please ask him if you want to know what he is doing right now; it should be cool!

By the way for KIT, we have to change the project again since our project now of analyzing past papers might take too long and if we cannot make it by the end of the year, there is a possibility that we might not get a service credit. Also, it is questionable if everyone uses it. 

In order to get a service credit, we have to engage in a project that contributes to a wider community. Therefore, I am currently discussing a new project that might involve the wider community with Ms. Wakasa and Mr. Cowe.

If you have any ideas for the new project, please let me know and we might be able to do it! I have also asked this to Tyler and he said it would be great if we can integrate SDGs theme into our project. Are you also interested in SDGs?

Tatsunori

**Comment by Tatsunori-Ono** [comment]
Btw, I think this code here is for the KIT Website and other Tyler's work!

**Comment by Andrewzekid** [comment]
Wow, thats pretty cool. As for analyzing past papers, are we just extracting the text from them?
